#theme = "gruvbox-dark"
icons = "awesome"

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Pop by Chris Kempson (http://chriskempson.com)

[theme]
name = "gruvbox-dark"  
[theme.overrides]
#separator = "  "       
#separator_fg = "#202020"
#separator_bg = "#202020"
idle_bg = "#202020"
idle_fg = "#d0d0d0"
info_bg = "#00aabb"
info_fg = "#161616"
good_bg = "#37b349"
good_fg = "#161616"
warning_bg = "#f8ca12"
warning_fg = "#161616"
critical_bg = "#eb008a"
critical_fg = "#161616"
# The rest of the theme settings are left at default.

#[[block]]
#block = "custom"
#command = "mocp -Q '%title [%state]'"
#on_click = "mocp -G"
#interval = 1

[[block]]
block = "custom"
#command = "mpc status | sed '/^volume:/d' | tac | sed 's/ #.*//' | tr '\n' ' '"
command = "mpc | sed '/^volume:/d' | head -1"
#on_click = "mpc toggle"
#on_click =  "mpc | sed '/^volume:/d' | head -1 | notify-send"
interval = 1

#[[block]]
#block = "music"
##player = "mpd"
#max_width = 32
#marquee_interval = 2
#marquee_speed = 0.25
#buttons = ["prev", "play", "next"]

#[[block]]
#block = "weather"
##format = "{weather} ({location}) {temp}°"
#format = "{weather} {temp}°"
#service = { name = "openweathermap", api_key = "6632b2a97378ae82a0dfe3966b4ec684", city_id = "690548", units = "metric" }

[[block]]
block = "net"
device = "wlp61s0"
ssid = true
bitrate = false
ip = true
speed_up = false
speed_down = false
graph_up = false
graph_down = false
interval = 1

[[block]]
block = "temperature"
collapsed = false
interval = 5
#format = "{min}° min, {max}° max, {average}° avg"
format = "{average}°"
good = 20
idle = 50
info = 65
warning = 80 # critical 100
chip = "coretemp-isa-0000"

[[block]]
block = "load"
interval = 1
format = "{1m} {5m}"

[[block]]
block = "cpu"
interval = 1
frequency = true

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mug}GiB"
format_swap = "{SUg}GiB"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 10.0
alert = 5.0

[[block]]
block = "disk_space"
path = "/home"
alias = "~"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

#[[block]]
#block = "xrandr"
#icons = true
#resolution = true
#interval = 2

[[block]]
block = "sound"
driver = "pulseaudio"
step_width = 1

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"
#format = "%F %R"

[[block]]
block = "uptime"

